apiVersion: v1
kind: Service
metadata:
  name: devops-intern-service
spec:
  type: LoadBalancer
  selector:
    app: devops-intern-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
